### ISSUE TITLE
#6 Create Delete Button

### ISSUE THREAD

**Issue by Anita77777** [Anita77777/capstone-project#11]
### Value Proposition

As a reader
I need a delete button to be able to delete book cards.

### Description
![DeleteButton](https://user-images.githubusercontent.com/101524703/169486903-93f61dea-7f45-459c-b7c5-18fcca3fb046.png)

### Acceptance Criteria

- [ ] Delete button is present , recognizable, and clickable
- [ ] If the delete button is pressed, the bookcard gets deleted

### Tasks

- [ ] Add a delete button with an on-Click event to the book-card
- [ ] Build click events on button that deletes the card
- [ ] Add the delete button to Storybook, as well as the new modifiable book "cards"

Complexity

S

**Comment by HishamAlmannai** [comment]
Hi Anita,

I am missing the"to be able to" in Value Proposition.

You could add another picture for the Confirmation handling

The Pop-up isn't described enough: one/two buttons? which is selected by default?
Does the Button gets deleted or archived in the database?

Maybe you could move some descriptions to the acceptance criteria (see above).
Does the Button have a different design? If so add to storybook.
It would be more interesting to try to add the pop-up to the storybook.
Any testing?

**Comment by Anita77777** [comment]
Hi Hisham, 

thanks for the remarks. I will not add a pop up after all so that topic is obsolete. Storybook is already added in the Tasks. Testing will be another User Story as I'm waiting for the workshop and then add all the testing for all the components:-)

**Comment by HishamAlmannai** [comment]
Hi Anita,

Value Proposition is still incomplete.

If you do not want to you a confirmation pop-up in future why implement it? 

Anyway approved.
