### ISSUE TITLE
#7 Edit Button toggle to save button

### ISSUE THREAD

**Issue by Anita77777** [Anita77777/capstone-project#12]
### Value Proposition

As a reader
I need an edit button to be able to edit the comment about the book (why I liked the book, key details about the story, etc. ) in my book card

### Description
![EditButton(1)](https://user-images.githubusercontent.com/101524703/169501658-682be3a3-b7d4-495c-8eec-2f26c7ef2fab.png)

### Acceptance Criteria

- [ ] Edit button is present , recognizable, and clickable
- [ ] When the edit button is pressed, I can edit the whole content of my comment
- [ ] Save button is present , recognizable, and clickable
When the save button is pressed, I can save the latest changes to my comment

### Tasks

- [ ] Create new branch Edit
- [ ] Add an edit button with an on-Click event in the card component  
- [ ] Add the edit button to Storybook

Complexity

S
