### ISSUE TITLE
#8 Refactoring styled components + Typography 

### ISSUE THREAD

**Issue by Anita77777** [Anita77777/capstone-project#16]
Refactoring styled components

**Comment by Anita77777** [comment]
### Value Proposition
As a developer
I need to have a clean structure of my styled components and a Typography component
to be able to organize different typo styles in a reusable and clearly arranged way.

### Description

For having a structured and reusable typography elements in my app, I need the Typography component that renders the respective styling.


### Acceptance Criteria

- [ ] All Typography components are reusable

### Tasks
- [ ] Create an UI structure and folder
- [ ] Create a Typography component inside the UI folder
- [ ] Write the Typography function and the variables including the already existing elements
- [ ]  Refactor the existing styled components

Complexity

S
