### ISSUE TITLE
#9 Split Pages for categories

### ISSUE THREAD

**Issue by Anita77777** [Anita77777/capstone-project#17]

**Comment by Anita77777** [comment]
### Value Proposition

As a reader
I need to have seperate pages for the categories "Home" "search" "loved" "disliked" "Want to read" and a footer with clickable icons
to be able to have a better overview in the app and the possibility to navigate easier.

### Description


![splitpages(1)](https://user-images.githubusercontent.com/101524703/170950098-0d94012e-8cbe-4c70-aaaa-c20f1a5791fb.png)

### Acceptance Criteria

- [ ] Pages displayed: Homescreen, Form with searchbar, "Loved" "Disliked" "Want to read" the entries are on seperate pages
- [ ] Implemented in the footer navbar are icons that show wich page is wich
- [ ] By clicking on the respective icon the reader is navigated to the page    

### Tasks

- [ ] Split the existing page in 5 pages
- [ ] Add a footer component
- [ ] Add the 5 icons and link them to the respective page in the navigation bar
- [ ] Add component to the index.js
- [ ]  Add styled-components
- [ ]  Add to Storybook
- [ ] Add testing

  




### Complexity

M

**Comment by alexclaes** [comment]
Hi Anita – great user story!

If I’m not mistaking you don’t have a search functionality yet. Please remember: you should not add any buttons without functionality.. You might want to remove the “search” from this story and the navigation bar for the time being. I advice to create an additional user story to add the search functionality later on.

Also, please don’t forget to write tests. You might want to add this to the “tasks” section of your user story.

Small UX advice: The home page is supposed to show the form to add a new book, right? Having a “house” icon in the navigation might be confusing. Consider adding using something more descriptive, like a “plus” icon

**Comment by Anita77777** [comment]
Hi Alex, appreciate your input.

The search bar will be implemented by the time I'll work on this user story. 
I will also have a home screen (now included in the description:-). I will use the plus icon instead of the home button
Added the testing to my tasks

**Comment by irenepapaspyratos** [comment]
As I understand, the buttons yet without function WILL be working upon starting with this branch, it looks very good to me. 😊

**Comment by alexclaes** [comment]
Okay 👌
