### ISSUE TITLE
Add bookmark buttons #3

### ISSUE THREAD

**Issue by Anita77777** [Anita77777/capstone-project#4]
### **Value Proposition**

As a reader
I need bookmark buttons to be able to mark the book as "loved" "didn't love" or "want to read". 

### **Description**
![Second Page](https://user-images.githubusercontent.com/101524703/167390287-401384e8-bfe6-4125-b9a1-7ff9d886b959.png)

### **Acceptance Criteria**

Each card should have a bookmark button

### **Tasks**

- [ ] Create bookmark buttons that can be clicked and stay marked
- [ ] Add to card component
- [ ] Add to Storybook
- [ ] Write test for each bookmark button
- [ ]   Add basic styling

### **Complexity**

M
