### ISSUE TITLE
#2 Add Bookmarkbutton

### ISSUE THREAD

**Issue by Anita77777** [Anita77777/capstone-project#4]
### Value Proposition

As a reader I need bookmark buttons to be able to bookmark whether i liked, didn't like or want to read the book. I

### Description
![BookmarkButtons](https://user-images.githubusercontent.com/101524703/168484247-4d2ade3c-ceff-449b-ad0e-54a1e99e37e1.png)

### Acceptance Criteria

- [ ] After adding the bookmark button the reader will be able to bookmark the book as loved, didn't love, want to read on the Card.

### Tasks

(for developers team)

- [ ] Create new branch "Bookmark"
- [ ] Add Bookmark to form component
- [ ] Icons will be used as buttons (style not defined yet)
- [ ]  Write the functions: toggle bookmark wich toggles between the buttons "loved" "didn't love" or "want to read"
- [ ] Add to storybook
- [ ] Carry out tests for the bookmark buttons
- [ ] Add basic styling via styled.components

Complexity

S

**Comment by irenepapaspyratos** [comment]
You could specify, to which component you want to add the buttons and I think, you should specify, what kind of buttons you want to use - radios (to force only one being able to be active) or real buttons (2 or even all can be active the same time) or a styled div, that is clickable... so many options... 
Besides that, it looks good to me. :)
