### ISSUE TITLE
#5 Add Searchbar

### ISSUE THREAD

**Issue by Anita77777** [Anita77777/capstone-project#8]
### Value Proposition

As a reader I need a searchbar to be able to search for books wich are provided by an api.

   
### Description
![SearchBar](https://user-images.githubusercontent.com/101524703/169012727-267ebd04-3290-44b2-a042-b8c526ce93e3.png)

### Acceptance Criteria

 

- [ ] The googlebook.api gets embedded
- [ ] The searchbar is displayed on the page of my form
- [ ] By typing in the name of the book or author a list of suggestions, provided by the googlebook.api is displayed where I can choose the book I want via click
- [ ] After choosing the book it is displayed in the form with Booktitle, Author and Bookcover

### Tasks

- [ ] Create new branch "Search-Book"
- [ ] Embed Googlebook.API into the component Form (probably with Axios)
- [ ] Create a search bar with a hidden list element
- [ ] Add the search icon to the search bar
- [ ]  Programm the event that shows the result on click
- [ ] Ensure the API renders the Author, Title and Bookcover and displays it in the form
- [ ] Adjust the form accordingly so the data displays properly
- [ ] Add basic styling
- [ ] Add to storybook

### Complexity

L
